export type Strain = {
  id: string;
  slug: string;
  name: string;
  lineage: string;
  mother: string;
  father: string;
  type: string;
  flow: string;
  yield: string;
  thc: string;
  terpenes: string;
  aroma: string;
  status: string;
  description: string;
  image: string;
  images?: string[];
};

export const STRAIN_DB: Strain[] = [
  { id: "OGS-001", slug: "jawa-pie", name: "JAWA PIE", lineage: "Key Lime Pie x Alien Rift", mother: "Key Lime Pie", father: "Alien Rift", type: "Indica Dominant", flow: "56-63 Days", yield: "High", thc: "22-26%", terpenes: "Limonene, Caryophyllene, Myrcene", aroma: "Lime, Gas, Earthy Kush, Graham Cracker", status: "Active", description: "Jawa Pie is a formidable indica-dominant hybrid resulting from the careful cross pollination of Key Lime Pie and our flagship male, Alien Rift.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/JAWAPIE-1-web-300x300.jpg" },
  { id: "OGS-002", slug: "vader-og", name: "VADER OG", lineage: "Vader Kush x Ocean Grown #3", mother: "Vader Kush", father: "Ocean Grown #3", type: "Hybrid", flow: "60-70 Days", yield: "Medium", thc: "24-28%", terpenes: "Myrcene, Limonene, Linalool", aroma: "Lemon, Pine, Deep Earth, Classic Kush Fuel", status: "Archived", description: "Vader OG is the crown jewel of classic Ocean Grown genetics.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/Vader-OG-3-web-300x300.jpg" },
  { id: "OGS-003", slug: "alien-rift", name: "ALIEN RIFT", lineage: "Alien Abduction x Alien Dawg x Alien OG", mother: "Alien Abduction", father: "Alien Dawg x Alien OG", type: "Indica", flow: "56-60 Days", yield: "High", thc: "25-29%", terpenes: "Caryophyllene, Myrcene, Humulene", aroma: "Spicy Hash, Skunk, Sour Lemon", status: "Active", description: "Alien Rift is an absolute resin factory and our most utilized breeding stud.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/alien-rift-web-300x300.jpg" },
  { id: "OGS-004", slug: "obi-wan-og", name: "OBI WAN OG", lineage: "Ghost OG x Alien Rift", mother: "Ghost OG", father: "Alien Rift", type: "Hybrid", flow: "65-75 Days", yield: "High", thc: "26-30%", terpenes: "Limonene, Caryophyllene, Pinene", aroma: "Citrus, Gas, Floral Pine", status: "Active", description: "Obi Wan OG merges the legendary, euphoric Ghost OG cut with the resinous power of our Alien Rift male.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/obiwan-og-300x300.jpg" },
  { id: "OGS-005", slug: "dark-plasma", name: "DARK PLASMA", lineage: "Forum GSC x Obiwan OG Kush", mother: "Forum GSC", father: "Obiwan OG Kush", type: "Indica Dominant", flow: "63-70 Days", yield: "Medium/High", thc: "24-28%", terpenes: "Caryophyllene, Linalool, Myrcene", aroma: "Sweet Dough, Chocolate, Fuel", status: "Active", description: "Dark Plasma captures the famed Forum Cut Girl Scout Cookies structure and infuses it with the yield and trichome density of Alien Rift.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/dark-plasma-2-300x300.jpg" },
  { id: "OGS-007", slug: "dreadnought", name: "DREADNOUGHT", lineage: "Fader Actual x Obiwan OG", mother: "Fader Actual", father: "Obiwan OG", type: "Hybrid", flow: "60-65 Days", yield: "High", thc: "24-28%", terpenes: "Limonene, Caryophyllene", aroma: "Lemon, Gas", status: "Active", description: "High yielding hybrid with massive resin production.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2021/12/dreadnought-web-300x300.jpg" },
  { id: "OGS-008", slug: "yoda-soda", name: "YODA SODA", lineage: "Merlot OG x Jawa Pie", mother: "Merlot OG", father: "Jawa Pie", type: "Hybrid", flow: "60-70 Days", yield: "Medium/High", thc: "22-26%", terpenes: "Myrcene", aroma: "Sweet, Citrus, Fizz", status: "Active", description: "A highly aromatic cultivar that fizzes on the palate.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2021/06/yoda-soda-web-300x300.jpg" },
  { id: "OGS-009", slug: "bear-mace", name: "BEAR MACE", lineage: "BB #3 x Wizard's Glue", mother: "BB #3", father: "Wizard's Glue", type: "Indica Dominant", flow: "60-65 Days", yield: "High", thc: "25-30%", terpenes: "Caryophyllene", aroma: "Spicy, Gas, Hash", status: "Active", description: "A heavy hitter with dense colas.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2021/12/bear-mace-web-300x300.jpg" },
  { id: "OGS-010", slug: "jawa-juice", name: "JAWA JUICE", lineage: "Jawa Pie x Unknown", mother: "Jawa Pie", father: "Alien Rift", type: "Hybrid", flow: "56-65 Days", yield: "Medium", thc: "22-26%", terpenes: "Limonene", aroma: "Lime, Gas", status: "Active", description: "A resinous offspring of Jawa Pie.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2021/06/jawa-juice-web-01-300x300.jpg" },
  { id: "OGS-011", slug: "kauai-electrics", name: "KAUAI ELECTRICS", lineage: "Unknown", mother: "Hawaiian", father: "Hawaiian", type: "Sativa", flow: "70-80 Days", yield: "High", thc: "18-22%", terpenes: "Terpinolene", aroma: "Tropical, Haze", status: "Active", description: "Pure tropical sativa energy.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2020/02/kauai-electrics-vdr-01-300x300.jpg" },
  { id: "OGS-012", slug: "maui-wowie", name: "MAUI WOWIE", lineage: "Hawaiian Landrace", mother: "Hawaiian", father: "Hawaiian", type: "Sativa", flow: "70-75 Days", yield: "Medium/High", thc: "20-24%", terpenes: "Myrcene, Limonene", aroma: "Pineapple, Citrus", status: "Active", description: "Classic tropical profile from Hawaii.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2020/03/maui-wowie-02-1-300x300.jpg" },
  { id: "OGS-013", slug: "molten-core", name: "MOLTEN CORE", lineage: "Ringo's Gift x Shockwave", mother: "Ringo's Gift", father: "Shockwave", type: "Indica Dominant", flow: "60-65 Days", yield: "High", thc: "24-28%", terpenes: "Caryophyllene", aroma: "Earth, Gas", status: "Active", description: "Deeply relaxing with fiery hairs.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/molten-core-web-02-300x300.jpg" },
  { id: "OGS-014", slug: "solar-sugar", name: "SOLAR SUGAR", lineage: "Jawa Pie #3 x Obiwan OG Kush", mother: "Jawa Pie #3", father: "Obiwan OG Kush", type: "Hybrid", flow: "60-70 Days", yield: "Medium", thc: "22-26%", terpenes: "Limonene", aroma: "Sweet, Citrus", status: "Active", description: "Bright, uplifting, and coated in sugar.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2021/03/solar-sugar-sq-300x300.png" },
  { id: "OGS-015", slug: "viking-pie", name: "VIKING PIE", lineage: "Unknown x Jawa Pie", mother: "Sugar Black Rose", father: "Jawa Pie", type: "Indica Dominant", flow: "60-65 Days", yield: "High", thc: "24-28%", terpenes: "Myrcene", aroma: "Berry, Dough", status: "Active", description: "A warrior's yield with baker's aromas.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2021/02/viking-pie-300x300.jpg" },
  { id: "OGS-016", slug: "dark-helmet", name: "DARK HELMET", lineage: "Forum GSC x Obiwan OG Kush", mother: "Forum GSC", father: "Obiwan OG Kush", type: "Indica Dominant", flow: "60-65 Days", yield: "Medium", thc: "26-30%", terpenes: "Caryophyllene", aroma: "Cookie Dough, Lime", status: "Active", description: "Dark, dense, and dangerously potent.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/Dark-Helmet-2-300x300.jpg" },
  { id: "OGS-017", slug: "dough-g", name: "DOUGH-G", lineage: "Forum GSC x VaderOG", mother: "Forum GSC", father: "VaderOG", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "22-26%", terpenes: "Myrcene", aroma: "Sweet Dough", status: "Active", description: "Sticky and sweet.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/dough-g-01-300x300.jpg" },
  { id: "OGS-018", slug: "dreaded-pie", name: "DREADED PIE", lineage: "Dreadnought OG x Jawa Pie", mother: "Dreadnought OG", father: "Jawa Pie", type: "Hybrid", flow: "60-65 Days", yield: "High", thc: "24-28%", terpenes: "Limonene", aroma: "Lemon, Dough", status: "Active", description: "Massive colas smelling of citrus dough.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2025/10/Dreaded-Pie-1-300x300.jpg" },
  { id: "OGS-019", slug: "fader-actual", name: "FADER ACTUAL", lineage: "Vader OG x Vader OG x Vader OG", mother: "Cookie Dough", father: "OG Kush", type: "Hybrid", flow: "60-70 Days", yield: "Medium/High", thc: "22-26%", terpenes: "Myrcene", aroma: "Gas, Floral", status: "Active", description: "A well-balanced hybrid.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/11/fader-actual-1-web-300x300.jpg" },
  { id: "OGS-020", slug: "highlander", name: "HIGHLANDER", lineage: "Witches Brew 'Highlander' x Vader OG", mother: "Witches Brew 'Highlander'", father: "Vader OG", type: "Hybrid", flow: "65-75 Days", yield: "High", thc: "24-28%", terpenes: "Pinene", aroma: "Pine, Earth", status: "Active", description: "There can be only one.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/highlander-web-01-300x300.jpg" },
  { id: "OGS-021", slug: "jawa-kush", name: "JAWA KUSH", lineage: "Ghost OG x Jawa Pie", mother: "Ghost OG", father: "Jawa Pie", type: "Indica Dominant", flow: "56-65 Days", yield: "Medium/High", thc: "24-28%", terpenes: "Caryophyllene", aroma: "Gas, Lime", status: "Active", description: "A heavy kush backcross.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/jawa-kush-2-300x300.jpg" },
  { id: "OGS-100", slug: "astrochimp", name: "ASTROCHIMP", lineage: "Gorilla Glue #4 x Alien Rift", mother: "Gorilla Glue #4", father: "Alien Rift", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: ASTROCHIMP. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-101", slug: "challenger-deep", name: "CHALLENGER DEEP", lineage: "Star Destroyer OG x Wizard's Glue", mother: "Star Destroyer OG", father: "Wizard's Glue", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: CHALLENGER DEEP. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-102", slug: "cthulhu", name: "CTHULHU", lineage: "Ghost OG x Witches Brew", mother: "Ghost OG", father: "Witches Brew", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: CTHULHU. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-103", slug: "devils-tear", name: "DEVILS TEAR", lineage: "Zenfandel OG x Alien Rift", mother: "Zenfandel OG", father: "Alien Rift", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: DEVILS TEAR. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-104", slug: "jedi-og", name: "JEDI OG", lineage: "Jedi OG x Vader OG", mother: "Jedi OG", father: "Vader OG", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: JEDI OG. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-105", slug: "malibrew", name: "MALIBREW", lineage: "Witches Brew 'Highlander' X Malibu Pie", mother: "Malibu Pie", father: "Witches Brew", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: MALIBREW. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-106", slug: "malibu-pie", name: "MALIBU PIE", lineage: "( Malibu Pie (Clone only F1 Cultivar) x Jawa Pie )", mother: "( Malibu Pie (Clone only F1 Cultivar)", father: "Jawa Pie )", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: MALIBU PIE. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-107", slug: "man-o-war", name: "MAN O WAR", lineage: "Bruce Banner #3 x Alien Rift", mother: "Bruce Banner #3", father: "Alien Rift", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: MAN O WAR. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-108", slug: "merlot-og", name: "MERLOT OG", lineage: "Larry OG x SFV OG", mother: "Larry OG", father: "SFV OG", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: MERLOT OG. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-109", slug: "shockwave", name: "SHOCKWAVE", lineage: "Alien Abduction x Witches Brew", mother: "Alien Abduction", father: "Witches Brew", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: SHOCKWAVE. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-110", slug: "skunkbeard", name: "SKUNKBEARD", lineage: "Animal Cookies x Alien Rift", mother: "Animal Cookies", father: "Alien Rift", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: SKUNKBEARD. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-111", slug: "sleeping-dog", name: "SLEEPING DOG", lineage: "Chemdawg x Alien Rift", mother: "Chemdawg", father: "Alien Rift", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: SLEEPING DOG. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-112", slug: "sticky-shrimp", name: "STICKY SHRIMP", lineage: "White Widow x Alien Rift", mother: "White Widow", father: "Alien Rift", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: STICKY SHRIMP. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-113", slug: "swashbuckler", name: "SWASHBUCKLER", lineage: "Forum GSC X Alien Rift", mother: "Merlot OG", father: "Alien Rift", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: SWASHBUCKLER. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-114", slug: "thunderfury", name: "THUNDERFURY", lineage: "Tropic Lightning x Shockwave", mother: "Tropic Lightning", father: "Shockwave", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: THUNDERFURY. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-115", slug: "tropic-lightning", name: "TROPIC LIGHTNING", lineage: "Malibu x Obiwan OG Kush", mother: "Malibu", father: "Obiwan OG Kush", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: TROPIC LIGHTNING. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-116", slug: "tropic-moon", name: "TROPIC MOON", lineage: "Maui Wowie x Alien Rift", mother: "Maui Wowie", father: "Alien Rift", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: TROPIC MOON. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-117", slug: "vaders-vintage", name: "VADERS VINTAGE", lineage: "Vader OG x Witches Brew", mother: "Vader OG", father: "Witches Brew", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: VADERS VINTAGE. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-118", slug: "wizards-glue", name: "WIZARDS GLUE", lineage: "GG4 x Wizard's Potion", mother: "GG4", father: "Wizard's Potion", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: WIZARDS GLUE. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-119", slug: "wolf-mother", name: "WOLF MOTHER", lineage: "Chemdawg x Witches Brew", mother: "Chemdawg", father: "Witches Brew", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: WOLF MOTHER. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-120", slug: "tahoe-abduction", name: "TAHOE ABDUCTION", lineage: "Tahoe OG x Alien Abduction", mother: "Tahoe OG", father: "Alien Abduction", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: TAHOE ABDUCTION. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-121", slug: "witches-brew", name: "WITCHES BREW", lineage: "Zenfandel OG x Merlot OG", mother: "Zenfandel OG", father: "Merlot OG", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: WITCHES BREW. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-122", slug: "witch-hunt", name: "WITCH HUNT", lineage: "Tahoe OG x SFV OG x Wizards Potion x Zenfandel x Merlot V", mother: "Witches Brew", father: "Alien Rift", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: WITCH HUNT. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-123", slug: "wizards-potion", name: "WIZARDS POTION", lineage: "Widow x Witches Brew", mother: "Widow", father: "Witches Brew", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: WIZARDS POTION. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" },
  { id: "OGS-124", slug: "zenfandel-og", name: "ZENFANDEL OG", lineage: "Tahoe OG x SFV OG", mother: "Tahoe OG", father: "SFV OG", type: "Hybrid", flow: "60-70 Days", yield: "High", thc: "20-25%", terpenes: "Myrcene, Caryophyllene", aroma: "Earthy, Gas", status: "Active", description: "A classic Ocean Grown hybrid: ZENFANDEL OG. Detailed phenotype data pending.", image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" }
];