export const STRAIN_DB = [
  { 
    id: "OGS-001", 
    slug: "jawa-pie",
    name: "JAWA PIE", 
    lineage: "Key Lime Pie x Alien Rift", 
    mother: "Key Lime Pie",
    father: "Alien Rift",
    type: "Indica Dominant", 
    flow: "56-63 Days", 
    yield: "High", 
    thc: "22-26%", 
    terpenes: "Limonene, Caryophyllene, Myrcene",
    aroma: "Lime, Gas, Earthy Kush, Graham Cracker",
    status: "Active", 
    description: "Jawa Pie is a formidable indica-dominant hybrid resulting from the careful cross pollination of Key Lime Pie and our flagship male, Alien Rift. The progeny expresses tight, golf-ball sized calyxes dripping in resin with a distinct aroma of lime-infused fuel and sweet dough. Expect rigorous vegetative growth and significant stretch during the first two weeks of flower.",
    image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/JAWAPIE-1-web.jpg" 
  },
  { 
    id: "OGS-002", 
    slug: "vader-og",
    name: "VADER OG", 
    lineage: "Ocean Grown Kush x SFV OG", 
    mother: "Ocean Grown Kush",
    father: "SFV OG",
    type: "Hybrid", 
    flow: "60-70 Days", 
    yield: "Medium", 
    thc: "24-28%", 
    terpenes: "Myrcene, Limonene, Linalool",
    aroma: "Lemon, Pine, Deep Earth, Classic Kush Fuel",
    status: "Archived", 
    description: "Vader OG is the crown jewel of classic Ocean Grown genetics. Known for its intense, quintessential OG Kush profile—heavy pine, lemon, and deep earth fuel. This strain provides a potent, full-body euphoria. It requires some structural support late in flower due to the heavy, dense colas.",
    image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/Vader-OG-3-web.jpg" 
  },
  { 
    id: "OGS-003", 
    slug: "alien-rift",
    name: "ALIEN RIFT", 
    lineage: "Alien Abduction x Alien Dawg x Alien OG", 
    mother: "Alien Abduction",
    father: "Alien Dawg x Alien OG",
    type: "Indica", 
    flow: "56-60 Days", 
    yield: "High", 
    thc: "25-29%", 
    terpenes: "Caryophyllene, Myrcene, Humulene",
    aroma: "Spicy Hash, Skunk, Sour Lemon",
    status: "Active", 
    description: "Alien Rift is an absolute resin factory and our most utilized breeding stud. This strain produces incredible hash returns with an intoxicatingly spicy, skunky, and sour lemon profile. The structure is squat and incredibly vigorous, producing frosty, rock-hard buds with little to no training required.",
    image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/alien-rift-web.jpg" 
  },
  { 
    id: "OGS-004", 
    slug: "obi-wan-og",
    name: "OBI WAN OG", 
    lineage: "Ghost OG x Alien Rift", 
    mother: "Ghost OG",
    father: "Alien Rift",
    type: "Hybrid", 
    flow: "65-75 Days", 
    yield: "High", 
    thc: "26-30%", 
    terpenes: "Limonene, Caryophyllene, Pinene",
    aroma: "Citrus, Gas, Floral Pine",
    status: "Active", 
    description: "Obi Wan OG merges the legendary, euphoric Ghost OG cut with the resinous power of our Alien Rift male. The result is a high-yielding, incredibly potent hybrid that carries a dominant gas and floral pine nose. It stretches significantly in early flower but rewards the grower with massive, frosted spears.",
    image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/obiwan-og.jpg" 
  },
  { 
    id: "OGS-005", 
    slug: "dark-plasma",
    name: "DARK PLASMA", 
    lineage: "Girl Scout Cookies (Forum Cut) x Alien Rift", 
    mother: "Girl Scout Cookies",
    father: "Alien Rift",
    type: "Indica Dominant", 
    flow: "63-70 Days", 
    yield: "Medium/High", 
    thc: "24-28%", 
    terpenes: "Caryophyllene, Linalool, Myrcene",
    aroma: "Sweet Dough, Chocolate, Fuel",
    status: "Active", 
    description: "Dark Plasma captures the famed Forum Cut Girl Scout Cookies structure and infuses it with the yield and trichome density of Alien Rift. Expect stunning dark purple and black hues late in flower, coated in a thick layer of frosty plasma. The aroma is a complex mix of sweet dough, faint chocolate, and intense fuel.",
    image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/dark-plasma-2.jpg" 
  },
  { 
    id: "OGS-006", 
    slug: "ninja-fruit",
    name: "NINJA FRUIT", 
    lineage: "Grapefruit Haze x Grape Ape", 
    mother: "Grapefruit Haze",
    father: "Grape Ape",
    type: "Sativa Dominant", 
    flow: "63-70 Days", 
    yield: "High", 
    thc: "20-24%", 
    terpenes: "Terpinolene, Myrcene, Ocimene",
    aroma: "Sweet Grape, Haze, Tropical Fruit",
    status: "Active", 
    description: "Ninja Fruit is a vibrant, uplifting Sativa-dominant hybrid. It brings together the massive yield and sweet tropical aromas of Grapefruit Haze with the deep purple hues and dense structure of Grape Ape. The result is a colorful, highly aromatic specimen perfect for daytime elevation.",
    image: "https://www.oceangrownseeds.com/wp-content/uploads/2019/10/seeds-edit-1400x788.jpg" 
  }
];
